//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSignUpLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TblUser
    {
        public long IntUserId { get; set; }

        [Required (ErrorMessage = "This field is required")]
        [Display(Name = "User Name")]
        public string StrUserName { get; set; }
        public string StrEmail { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string StrPassword { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "RePassword")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("StrPassword", ErrorMessage = "Confirm password doesn't match, type again !")]
        public string StrRePassword { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DteCreatedAt { get; set; }
        public Nullable<long> IntCreatedBy { get; set; }
        public Nullable<System.DateTime> DteUpdatedAt { get; set; }
        public Nullable<long> IntUpdatedBy { get; set; }
    }
}
